version: '3.8'

services:
  flixify-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flixify-app
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - flixify-network
    depends_on:
      - flixify-proxy

  flixify-proxy:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    container_name: flixify-proxy
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - flixify-network
    environment:
      - NODE_ENV=production
      - PORT=3001

networks:
  flixify-network:
    driver: bridge
